# Generated by Django 4.1.3 on 2022-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goroskop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goroskop',
            name='text',
            field=models.TextField(default='text'),
        ),
    ]
